# Generated by Django 5.0.4 on 2024-04-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_prompt",
            field=models.BooleanField(default=False),
        ),
    ]
